### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Rongmario** [quat1024/BotaniaTweaks#11]
[crash-2018-06-11_14.41.12-server.txt](https://github.com/quat1024/BotaniaTweaks/files/2090466/crash-2018-06-11_14.41.12-server.txt)

**Comment by quat1024** [comment]
Oh nooo

**Comment by quat1024** [comment]
Fix is under review on Curse as version 1.1.1, ~~should be available in 15 minutes I guess~~haha no curse is being slow af as usual.

Thanks for the report.

Next time please include what you were doing, I had to fool around for a bit to determine that the crash was caused by completing a terrasteel agglomeration recipe

**Comment by Rongmario** [comment]
It was reported by one of the players, sorry ^^
