### ISSUE TITLE
Agglomeration.removeDefaultRecipe(); does not work

### ISSUE THREAD

**Issue by plunginghornets** [quat1024/BotaniaTweaks#12]
I wasn't sure if the () was necessary, but I tried with and without. Without it just throws a null exception. With it says "ERROR: There was a problem applying a Botania Tweaks action.

**Comment by quat1024** [comment]
Found the bug! I was creating the default recipe object *after* CT scripts executed. The script ended up trying to remove a recipe which hadn't been defined yet, freaked out partway through the logging routine (oddly enough), and throwing a NullPointerException. Fixed it by just creating that recipe object earlier.

Thanks for the report. This will be fixed in the next release on Curseforge, I want to add some more things first though.

**Comment by plunginghornets** [comment]
I'm glad it wasn't just my lack of scripting knowledge. I'll keep an eye out for the update, thanks!

**Comment by quat1024** [comment]
Update's now live, as 1.3!
