### ISSUE TITLE
How to add Agglomeration Recipe?

### ISSUE THREAD

**Issue by PanSzelescik** [quat1024/BotaniaTweaks#13]
In my mod I want to add Agglomeration Recipes, but I do not know how. I need installed CraftTweaker? I would like to avoid it

**Comment by quat1024** [comment]
Hi!

CraftTweaker is required to add agglomeration recipes. You can find the documentation [here](https://github.com/quat1024/BotaniaTweaks/wiki/CraftTweaker-Agglomeration).

I don't have any plans to add a CraftTweaker-less way to add recipes (because it would basically just be reimplementing CraftTweaker)
