### ISSUE TITLE
[Suggestion] Minor tweaks to the Special Grasses

### ISSUE THREAD

**Issue by thephoenixlodge** [quat1024/BotaniaTweaks#35]
In the pack I'm working on, the starting island (skyblock) uses Infused grass as the surface and it take a while to get regular grass. However, there's been a few minor nuisances with it.
1. You cannot use a hoe to turn it into farmland. From what I can find on the Botania issue tracker, this is somewhat intentional, which is why I'm posting here.
2. You cannot place tree seeds from Dynamic Trees on it. Even if you break it and place down dirt to get the seed planted, if the grass spreads to that spot before the tree grows one stage, it'll cause it to pop off.

Neither of these are gamebreaking, but they certainly get annoying having to constantly break the grass to replace with dirt

**Comment by quat1024** [comment]
Interesting pack idea!

About tilling the farmland - it's probably doable, but since I'm neither the mod adding the hoes or the grass I might need some funny business. Probably doable, though.

About planting dynamic trees: A quick glance at the source of that mod, and it actually looks possible to assign new soil types to tree types, which is great.

While im playing with dynamic trees i might want to bang out #22 as well which currently is a pretty major exploit

**Comment by quat1024** [comment]
Thank you for the suggestions!

In the next update (version 1.8 approving on curse right now), you will be able to till infused grasses to create farmland by enabling `tillCustomGrass` in the `etc` category, and plant the dynamic trees seed thingies on infused grasses by enabling `customGrassTrees` in the `compat.dynamictrees` category.

Hoe tilling works on anything that fires the Forge `UseHoeEvent`, which vanilla hoes do. If modded hoes don't work, not my fault :wink:

And for the tree planting, basically, if you can plant the sapling on a grass block, I also add *all* of the Botania infused grass blocks. Unfortunately it's impossible to distinguish between different types of infused grass, but I don't think anyone really wants that anyways.

I was not able to fix the munchdew exploit BTW so keep that in mind (more details in #22 )

Thanks for making me download Dynamic Trees, by the way, really nice mod.
