### ISSUE TITLE
[Suggestion] Tiered Mana FluxField Blocks

### ISSUE THREAD

**Issue by ghost** [quat1024/BotaniaTweaks#54]
A fairly simple addition, add 2-3 blocks that are copies of the Mana FluxField, except with config options for their own Mana consumption and RF/tick generation, as well as progressively more expensive crafting recipes, and the ability to disable these blocks altogether. 
The idea being to add a bit more variance to FluxFields that would make it more viable to use Botania as the sole source of RF Gen, but configurable so that it’s only as broken as packdevs want it to be.

**Comment by quat1024** [comment]
I thought about this, but because Botania calls setRegistryName in the constructor of its blocks, it's decently annoying to create *more* copies of a block because every block needs a unique ID.

I also don't really like this idea; Botania very intentionally doesn't have any sort of "flat upgrades" like an "endoflame but it makes more mana" and I want to respect that.
