### ISSUE TITLE
Undefined model on Lexica Botanica Terrasteel page

### ISSUE THREAD

**Issue by nihiltres** [quat1024/BotaniaTweaks#7]
On one of the Lexica Botanica pages (Lexica Botanica > Basics > Terrasteel > p. 4/5), the multiblock for the agglomeration plate displays with a missing model where the agglomeration plate would normally display. This is *probably* due to you replacing the base agglomeration plate with your own, but I haven't checked carefully.

Since it's expected that pack authors might add custom structures for agglomeration plate recipes, I suggest and request implementing a tweaker function for custom agglomeration multiblock Lexicon pages (similar to my request in #6)… but at very least the default one should probably get fixed.

Thanks!

**Comment by quat1024** [comment]
Goddammit, I knew I would forget to check somewhere. Good catch.

That would definitely be due to me replacing the agglomeration plate. Due
to the way Botania is set up (no ObjectHolders) doing registry replacements
on it tends to need a little extra rejiggering to avoid cases like this.

I'll be away for a couple of days, but I'll play with it when I get back.

**Comment by quat1024** [comment]
This also seems to affect the multiblock structure preview, I can't actually complete the multiblock with the tweaked plate. Whups.

**Comment by quat1024** [comment]
This was surprisingly tricky to fix, since Botania creates multiblock structure previews basically *immediately* after the preinit stage. My fix is very hacky and I'm going to ask around if there's a better solution.

edit: The better solution is to beg for Botania to fix it for me lol
